web:
  build: web
  container_name: vars_web
  volumes:
    - ./web/vars-server:/docker/vars
  working_dir: /docker/vars
  ports:
    - "80:3000"
  links:
    - mongo

adminweb:
  build: adminweb
  container_name: admin_web
  volumes:
    - ./adminweb/admin-server:/docker/adminweb
  working_dir: /docker/adminweb
  ports:
    - "40125:40125"
  links:
    - mongo

mongo:
  build: mongo
  container_name: vars_mongo
  ports:
    - "27017:27017"
  volumes:
    - ./mongo/scripts:/docker/scripts
    - ./mongo/autobackup:/share/autobackup
    # - ./mongo/db:/data/db #データベースの永続化 Linux以外では動作しない
