//noinspection JSAnnotator
db = db.getSiblingDB("vars");
db.events.drop();
db.createCollection("events");
db.events.insert({
    Eventid:1,
    Eventname:"イベントA",
    Overview:"イベントAの説明です",
    Address:"test@example.com",
    displayName:"test",
    Course:"soft1",
    Venue:"南館1階B教室",
    Date:"2016/10/12",
    Createperiod:{
        Createstart:"2016/10/4",
        Createfinish:"2016/10/11"
    },
    Voteperiod:{
        Votestart:"2016/10/12",
        Votefinish:"2016/10/20"
    },
    Image:""
});
db.events.insert({
    Eventid:2,
    Eventname:"イベントB",
    Overview:"イベントBの説明です",
    Address:"test@example.com",
    displayName:"test",
    Course:"soft2",
    Venue:"ホワイエ",
    Date:"2016/10/21",
    Createperiod:{
        Createstart:"2016/10/12",
        Createfinish:"2016/10/20"
    },
    Voteperiod:{
        Votestart:"2016/10/21",
        Votefinish:"2016/10/31"
    },
    Image:""
});
db.events.insert({
    Eventid:3,
    Eventname:"イベントC",
    Overview:"イベントCの説明です",
    Address:"test@example.com",
    displayName:"test",
    Course:"game1",
    Venue:"ソニックホール",
    Date:"2016/11/1",
    Createperiod:{
        Createstart:"2016/10/21",
        Createfinish:"2016/10/31"
    },
    Voteperiod:{
        Votestart:"2016/11/1",
        Votefinish:"2016/11/10"
    },
    Image:""
});
